spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password:

  servlet:
    multipart:
      maxFileSize: 10MB
      maxRequestSize: 10MB

  sql:
    init:
      schema-locations: classpath:/data/schema_postgres.sql
      data-locations: classpath:/data/data.sql
      mode: always

mybatis:
  config-location: classpath:/mybatis-config.xml
  mapper-locations: classpath:/mapper/*.xml

logging.level.org.hibernate.orm.jdbc.bind: trace