spring:
  datasource:
    driver-class-name: org.h2.Driver
    #    url: jdbc:h2:mem:scheduler
    url: jdbc:h2:tcp://localhost/~/scheduler
    #    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    #    url: jdbc:log4jdbc:h2:tcp://localhost/~/scheduler
    username: sa
    password:

  servlet:
    multipart:
      maxFileSize: 10MB
      maxRequestSize: 10MB

  sql:
    init:
      schema-locations: classpath:/data/schema_h2.sql
      data-locations: classpath:/data/data.sql
      mode: always

  h2.console.enabled: true

mybatis:
  config-location: classpath:/mybatis-config.xml
  mapper-locations: classpath:/mapper/*.xml

logging.level.org.hibernate.orm.jdbc.bind: trace